### ISSUE TITLE
Extracting PI Point Tag

### ISSUE THREAD

**Issue by jbshiau235** [Hugovdberg/PIconnect#506]
Is there a way to extract information for a PIPoint like tag name or value as strings or numbers? I'm trying to narrow a list of PIPoints down based on tag names, but I want to keep the filter generic (i.e match filter via regular expressions) since I'm not always looking for a specific PI Tag, but rather a list of tags containing the same type of information (which therefore means the tag names should go by a similar format)

**Comment by Hugovdberg** [comment]
That's an interesting question. Yes, `PIPoint` , `PIAFElement` and `PIAFAttribute` objects all have a `name` attribute that contains the name of the item. For `PIPoint` objects this contains the tag name.
So something like this should work, hope that helps:

```python
import re
import PIconnect as PI

pattern = re.compile(r"FQI?[TS]?\d{3}")
with PI.PIServer() as server:
    points = [point 
              for point in server.search("*")
              if pattern.match(point.name)] # or pattern.match(point.tag)
```

**Comment by jbshiau235** [comment]
Perfect, that works for me. I was mainly struggling to find documentation regarding what kinds of attributes a PIPoint has that I can extract. Doing "point.tag" works for me as well as "point.current_value" to extract what value it has. I appreciate your help on this!

**Comment by Hugovdberg** [comment]
Note that the documentation contains a section `API Reference` that shows what methods and attributes the different kinds of objects have. The attributes should all have at least some description, if you're missing something please let me know!

I was going to suggest the following, but I noticed the mock API for the tests breaks the automatic detection of the right location:
~~If you find yourself lost in the API Reference because you don't know in which section a certain object lives, than it might help to navigate there from the tutorials. If you click on the bold class names in the tutorials they link to the exact location in the reference.~~

Finally, if you know/feel some attribute of an object is stored in the PI Server but it isn't currently available in `PIconnect`, then please let me know. If it is readily available in the PI AF SDK I can add it pretty quickly usually.

**Comment by jbshiau235** [comment]
What attributes can I pull from a PISeries data type? I looked at the API Reference, but it only tells me what parameters to put into a PISeries object. I'm looking to extract recorded values of PIPoint objects into a dictionary or list to put into a table with columns: Tag Name (string), Time Stamp (date/time), Value (either string or number). I can get the tag name from PISeries.tag, and value from PISeries[index] (after guessing around), but I can't seem to get the time stamp to come out. Is there a property I can use to pull that information?

**Comment by Hugovdberg** [comment]
The `PISeries` objects itself are not very informative, they are essentially a `pandas.Series` with very little additional info. They have an attribute `PISeries.tag` with the tag name, and `PISeries.uom` with the units of measurement, and the timestamps are used as the `PISeries.index` but more info is available from the `PIPoint` objects.

The `PIPoint` has the following attributes:
 - `current_value` & `last_update`: latest recorded value and the corresponding time stamp
 - `name`: the tag name
 - `description`: the description of the PI Point
 - `units_of_measurement`: the units of measurement of the values
 - `raw_attributes`: the raw attributes as reported by the PI SDK

But to get a table like you suggest there you could use something like the following snippet:

```python
with PI.PIServer() as server:
    point = server.search("*")
    data = point.recorded_values("-1d", "*")
data.reset_index().rename(columns={"index": "Time Stamp"}).melt(
    id_vars="Time Stamp", var_name="Tag Name", value_name="Value"
)
```

**Comment by jbshiau235** [comment]
Additional question regarding data extraction. Is it possible to pull an interpolated value for a PI Tag for a given single point in time? I know the reference shows you how to pull interpolated values over a time range, but I would like to know what the value was at a specific time stamp. I tried doing:

`point.interpolated_values(start_time=some_time, end_time=some_time, interval='0s')`

However, this didn't work since I believe this function only takes ranges with specified intervals. Ideally something like the current_value attribute would be nice, but for some time in the past history of the data.

**Comment by Hugovdberg** [comment]
Good question, I've never had the need for that, but I can look into that
tomorrow.

Op di 10 mrt. 2020 19:02 schreef Jayson Shiau <notifications@github.com>:

**Comment by Hugovdberg** [comment]
@jbshiau235 you can install the package from the feature branch using `pip install git+https://github.com/Hugovdberg/PIconnect@feature/feature/extract_single_historic_value`. Due to the coronacrisis I don't think I'll get around to merging it into the main branch and publishing a new version soon. Both `PIPoint` and `PIAFAttribute` have an attribute `recorded_time` and `interpolated_time`, that query the data for a single time. The documentation needs work, but hopefully this helps you get started!

**Comment by jbshiau235** [comment]
Perfect, thank you very much. Stay healthy!
